---
images:
  bash: docker.io/library/bash:latest
  builder: docker.io/paketobuildpacks/builder:base

annotations:
  tekton.dev/categories: Image Build
  tekton.dev/displayName: Buildpacks
  tekton.dev/pipelines.minVersion: "0.17.0"
  tekton.dev/platforms: linux/amd64
  tekton.dev/tags: image-build

# the CNB builder security context, by default it uses UID and GID 1000
securityContext:
  runAsUser: 1000
  runAsGroup: 1000

# pod-template (stepTemplate) to set resource limits on all steps, consider the resource limits
# defined here as the maximum amount of resources the image builder process will utilize, while the
# other steps won't need much resources
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi