---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildpacks
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
  annotations:
{{- if .Values.annotations }}
  {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  description: {{ .Chart.Description }}

  workspaces:
    - name: source
      description: Directory where application source is located.
    - name: cache
      description: Directory where cache is stored (when no cache image is provided).
      optional: true
    - name: bindings
      description: Extra PEM certificate file(s) ('*.pem')to create extra bindings.
      optional: true

  params:
    - name: APP_IMAGE
      description: The name of where to store the app image.
    - name: BUILDER_IMAGE
      description: The image on which builds will run (must include lifecycle and compatible buildpacks).
      default: "{{ .Values.images.builder }}"
    - name: SOURCE_SUBPATH
      description: A subpath within the `source` input where the source to build is located.
      default: ""
    - name: ENV_VARS
      type: array
      description: Environment variables to set during _build-time_.
      default: []
    - name: PROCESS_TYPE
      description: The default process type to set on the image.
      default: "web"
    - name: RUN_IMAGE
      description: Reference to a run image to use.
      default: ""
    - name: CACHE_IMAGE
      description: The name of the persistent app cache image (if no cache workspace is provided).
      default: ""
    - name: SKIP_RESTORE
      description: Do not write layer metadata or restore cached layers.
      default: "false"
    - name: USER_ID
      description: The user ID of the builder image user.
      default: "{{ .Values.securityContext.runAsUser }}"
    - name: GROUP_ID
      description: The group ID of the builder image user.
      default: "{{ .Values.securityContext.runAsGroup }}"
    - name: PLATFORM_DIR
      description: The name of the platform directory.
      default: empty-dir

  results:
    - name: APP_IMAGE_DIGEST
      description: The digest of the built `APP_IMAGE`.
    - name: APP_IMAGE_URL
      description: The URL of the built `APP_IMAGE`.

  volumes:
    - name: scripts-dir
      emptyDir: {}
    - name: empty-dir
      emptyDir: {}
    - name: layers-dir
      emptyDir: {}
    - name: bindings-dir
      emptyDir: {}

  stepTemplate:
    env:
      - name: CNB_PLATFORM_API
        value: "0.11"
      - name: SERVICE_BINDING_ROOT
        value: /bindings
{{- if .Values.resources }}
    resources:
  {{- .Values.resources | toYaml | nindent 6 }}
{{- end }}

  steps:
    # load all the shell scripts into the "/script" directory, a simple file creation followed by
    # adding execution permission
    - name: load-scripts
      image: {{ .Values.images.bash }}
      workingDir: /scripts
      script: |
{{- range $path, $content := .Files.Glob  "scripts/*.sh" }}
  {{- $name := trimPrefix "scripts/" $path }}
        printf '%s' "{{ $content | toString | b64enc }}" |base64 -d >{{ $name }}
        chmod +x "{{ $name }}"
{{- end }}
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts

    # prepare the filesytem and extra settings in order to perform the CNB builder as the next step,
    # extra enviroment variables are stored on the /platform/env following buildpacks convention
    - name: prepare
      image: {{ .Values.images.bash }}
      command:
        - /scripts/prepare.sh
      args:
        - "--env-vars"
        - "$(params.ENV_VARS[*])"
      # the enviroment variables required by the script are based on template
      env:
{{- include "environment-variables" . | nindent 8 }}
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
        - name: layers-dir
          mountPath: /layers
        - name: $(params.PLATFORM_DIR)
          mountPath: /platform
        - name: bindings-dir
          mountPath: /bindings

    # runs the primary entrypoint for the task, invokes the "creator" CNB entrypoint to perform the
    # whole lifecycle steps in order to build a new container image
    - name: create
      image: $(params.BUILDER_IMAGE)
      imagePullPolicy: Always
      command:
        - /cnb/lifecycle/creator
      args:
        - "-app=$(workspaces.source.path)/$(params.SOURCE_SUBPATH)"
        - "-cache-dir=$(workspaces.cache.path)"
        - "-cache-image=$(params.CACHE_IMAGE)"
        - "-uid=$(params.USER_ID)"
        - "-gid=$(params.GROUP_ID)"
        - "-layers=/layers"
        - "-log-level=debug"
        - "-no-color"
        - "-platform=/platform"
        - "-report=/layers/report.toml"
        - "-process-type=$(params.PROCESS_TYPE)"
        - "-skip-restore=$(params.SKIP_RESTORE)"
        - "-previous-image=$(params.APP_IMAGE)"
        - "-run-image=$(params.RUN_IMAGE)"
        - "$(params.APP_IMAGE)"
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
        - name: $(params.PLATFORM_DIR)
          mountPath: /platform
        - name: bindings-dir
          mountPath: /bindings
{{- if .Values.securityContext }}
      securityContext:
  {{- .Values.securityContext | toYaml | nindent 8 }}
{{- end }}

    # inspect and extract the lifecycle results stored on `/layers/report.toml`, the script looks for
    # the new image digest and URL (fully qualified image name)
    - name: report
      image: {{ .Values.images.bash }}
      command:
        - /scripts/report.sh
      env:
        - name: RESULTS_APP_IMAGE_DIGEST_PATH
          value: $(results.APP_IMAGE_DIGEST.path)
        - name: RESULTS_APP_IMAGE_URL_PATH
          value: $(results.APP_IMAGE_URL.path)
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
        - name: layers-dir
          mountPath: /layers
