name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v3

      - shell: bash
        run: make git-config

      - shell: bash
        run: make helm-package

      - uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: .
          skip_packaging: "true"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
