name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - shell: bash
        run: make install-chart-releaser

      - shell: bash
        run: make release
