---
name: test

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: azure/setup-helm@v3

      - name: test-integration
        run: make test-integration

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: azure/setup-helm@v3

      - uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind
          wait: 120s

      - uses: otaviof/setup-tekton@main
        with:
          tekton_version: v0.41.0
          cli_version: v0.29.1
          setup_registry: "true"
          registry_hostname: registry.registry.svc.cluster.local
          patch_etc_hosts: "true"

      - name: test-e2e
        run: make test-e2e
